### ISSUE TITLE
change plot_targets to plot_circles, make color an optional argument

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#114]
it is very difficult to plot circles of the correct size in pyplot for some reason, but the plot_targets function does a nice job of it. currently though it only uses one color, and the name implies it only does targets. could be made more general.

**Comment by zaicheek** [comment]
@leoscholl - branch gus_issue_114 occasionally passes plotting test with z-axis error on circles. I could use help debugging instability (might just be local machine animation issues you referenced) and figuring out z-axis error.

**Comment by leoscholl** [comment]
Ok I’ll take a look tomorrow. Probably my fault for using a somewhat questionable approach to dealing with both 2d and 3d axes.

**Comment by leoscholl** [comment]
@zaicheek would be helpful if you make a pull request so i can make comments there
