### ISSUE TITLE
success rate and event rate are not correct relative to trials

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#13]
success rate needs to be calculated on a per-trial basis rather than a per-event basis, otherwise it is not meaningful. the success rate function can take in a list of trials and figure out which ones have a success event in them, perhaps. 

also the documentation on these functions could be improved, e.g. here the description is not correct
https://github.com/aolabNeuro/analyze/blob/6e6071193b48b2d748cb7077e97138ed9100b181/aopy/preproc.py#L200-L203

and here the output doesn't have a type and isn't described
https://github.com/aolabNeuro/analyze/blob/6e6071193b48b2d748cb7077e97138ed9100b181/aopy/preproc.py#L246-L247

there are a couple more places, see ryan's comments on #12

**Comment by leoscholl** [comment]
hi si jia, any progress on fixing this issue?

**Comment by sijia66** [comment]
check the branch fix_event_rate with updated  calc_event_rate and its test function. Will the functions that work on task codes (i.e. a list of task codes as opposed to trial separated task codes) ever be useful?
