### ISSUE TITLE
Add a google colab ipynb to demonstrate how to use aopy in google colab

### ISSUE THREAD

**Issue by rcanfield2** [aolabNeuro/analyze#141]

**Comment by leoscholl** [comment]
the relevant line of code: `!pip install git+https://github.com/aolabNeuro/analyze.git`

**Comment by mmadduri** [comment]
Update: Sept 21 2021 - working on "first draft" of google colab:

- adding installation of aopy git
- add how to mount google drive to access data
- add test function (https://analyze.readthedocs.io/en/latest/preproc.html?highlight=detect%20edges#aopy.preproc.detect_edges)
- download as a python notebook and put it into the examples

**Comment by mmadduri** [comment]
Sample Google Colab Notebook: https://colab.research.google.com/drive/1ivOTa0YPRVQ-HB5cuTwnhgJEvULNxmKJ?usp=sharing
