### ISSUE TITLE
add function to bin spike times

### ISSUE THREAD

**Issue by rcanfield2** [aolabNeuro/analyze#215]

**Comment by rcanfield2** [comment]
Example code I have already written.

```
def bin_spike_times(spike_times, nbins, bin_width):
    binned_unit_spikes, _ = np.histogram(spike_times, bins=nbins, range=(0, nbins*bin_width))
    binned_unit_spikes = binned_unit_spikes/bin_width # convert from [spikes/bin] to [spikes/s]
    return binned_unit_spikes
```

**Comment by rcanfield2** [comment]
Would also be helpful if this function could output the indices corresponding to each bin.

**Comment by resatomo** [comment]
Is input data 1D time-series data? or should I assume trials and channels as well?

**Comment by rcanfield2** [comment]
It would probably be more useful if the function could take in data with multiple dimensions
