### ISSUE TITLE
default eye channel orderings are not the same in parse_oculomatic

### ISSUE THREAD

**Issue by pqz317** [aolabNeuro/analyze#225]
Hi all, is there a reason why these 2 eye channel orderings aren't the same in parse_oculomatic? 
https://github.com/aolabNeuro/analyze/blob/6e94b0ba4528b824085047dcf38a5c0a063a18af/aopy/preproc.py#L1297-L1300
For reference, if line 1297 is reached, then the eye_metadata returned is:
```
{'channels': [9, 8, 10, 11], 'labels': ['left_eye_x', 'left_eye_y', 'right_eye_x', 'right_eye_y'], 'samplerate': 25000, 'voltsperbit': 0.00030517578125}
```

**Comment by leoscholl** [comment]
1297 is correct, we swapped around the order of the channels (the physical wires coming from the camera system) at some point, which coincided with updating the metadata to automatically include those new channel numbers.

but i think 1300 should actually be [10, 11, 8, 9] for consistency with what's currently plugged into the recording system.

**Comment by pqz317** [comment]
Thank you, just for my understanding, why shouldn't 1297 and 1300 be the same? It seems like 1297 is for the case when an hdf file is specified, but bmi3d doesn't supply eye channel definitions, and 1300 is for when no hdf file is specified.

**Comment by leoscholl** [comment]
It’s an attempt at assigning the correct channels based on the date, maybe easier to explain in person once you get a chance to see the setup
