### ISSUE TITLE
Return data and metadata in proc_() functions

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#231]
See https://github.com/aolabNeuro/analyze/pull/227#pullrequestreview-854852350_

Similar return statements could be added to other preproc functions

**Comment by sijia66** [comment]
I am taking some notes to make this issue easier to resolve. 

for proc_exp: 
1. add save_res as an optional argument 
2. output bmi3d_data, bmi3d_metadata

for proc_mocap:
1.  add save_res as an optional argument 
2. output  optitrack_data and optitrack_metadata

for proc_lfp:
1.  add save_res as an optional argument 
2. output lfp_metadata, lfp_data

**Comment by leoscholl** [comment]
done for proc_exp()

**Comment by leoscholl** [comment]
need to think a bit more about whether this is actually useful. Currently the preprocessing functions always have to do work even if overwrite=False and the file already exists, since they need to return the data and metadata.
