### ISSUE TITLE
trial_align_data() outputs the wrong shape for single-channel or single-trial data

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#240]
should ensure that the output is always [ntrial x nt x nch] even if there is only one trial or one channel, otherwise downstream functions get confused.

**Comment by m-nolan** [comment]
https://github.com/aolabNeuro/analyze/blob/0d14115ca9d2b3afb676c74e0271dfd00a67c6c5/aopy/preproc/base.py#L304

@leoscholl when does this problem happen, and what does it typically look like? Is it that the first dimension (trials) is squeezed or that the channel dimension is squeezed? The code only looks like it would make the latter happen.
