### ISSUE TITLE
erp outputs data in the wrong convention

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#318]
analysis.calc_erp outputs (ntr, nt, nch) instead of (nt, ntr, nch)

**Comment by leoscholl** [comment]
i think the reason for this is that trial_align_data also outputs (ntr, nt, nch), we chose to do this so that the data could be n-dim, so any extra dimensions would get added at the end, e.g. (ntr, nt, nch, nunit). Is it worth keeping this functionality or should we just force data to be (nt, nfeat) where features can be channels, units, etc. all flattened?

**Comment by rcanfield2** [comment]
I think we should force the data to be (nt, nfeat).
