### ISSUE TITLE
add function to bin discrete events

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#84]
take in spike data; return binned spike rates in time. This should also work if data has already been trial aligned.

args: 
    spike times (nt, nch, (ntrial))
    bin width (time)
    
returns:
    (nbin, nch, (ntrial)) - binned spikes

**Comment by rcanfield2** [comment]
Write a basic function to bin spike data. 'waveform_data' is an (nt x 1) array of data. It would be useful to expand this function to accommodate higher dimensional arrays.

```
def bin_spikes(waveform_data, nbins, bin_width, total_time_s):
    binned_unit_spikes, _ = np.histogram(waveform_data, bins=nbins, range=(0, total_time_s))
    binned_unit_spikes = binned_unit_spikes/bin_width # convert from [spikes/bin] to [spikes/s]
    return binned_unit_spikes
```
