### ISSUE TITLE
add function to calculate firing rate

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#85]
Calculate firing rate of spike data. This should be compatible with regular spiking data and trial aligned spiking data

args:
    data (nt x nch x (ntrials))
    binwidth (int)

returns:
    (nt x nbin): spike rate over time

**Comment by rcanfield2** [comment]
I think the shape of the returned array should be (nbin x nch x (ntrials))

**Comment by leoscholl** [comment]
i think this is a duplicate of #84
